package events;

public enum FireEventName {
	NOTIFY_NO_HIGH_LADDER_TRUCK_AVAILABLE,
	NOTIFY_HIGH_LADDER_TRUCKS_AVAILABLE,
	NOTIFY_NO_STANDARD_TRUCK_AVAILABLE,
	NOTIFY_STANDARD_TRUCKS_AVAILABLE,
	FIRE_ALARM,
	FIRST_FIRE_ALARM,
	END_OF_FIRE,
	REQUEST_PRIORITY,
	AT_DESTINATION,
	AT_STATION,
	INTERVENTION_REQUEST;
}
