package events;

public enum HealthEventName {
	HEALTH_ALARM,
	TRACKING_ALARM,
	MANUAL_SIGNAL,
	REQUEST_PRIORITY,
	AT_DESTINATION,
	AT_STATION,
	NOTIFY_MEDICS_AVAILABLE,
	NOTIFY_NO_MEDIC_AVAILABLE,
	NOTIFY_AMBULANCES_AVAILABLE,
	NOTIFY_NO_AMBULANCE_AVAILABLE,
	INTERVENTION_REQUEST,
	CONSCIOUS_FALL,
	ALL_AMBULANCES_IN_INTERVENTION,
	ALL_MEDICS_IN_INTERVENTION,
	AMBULANCES_AVAILABLE,
	MEDICS_AVAILABLE;
}
